name: github pages

on:
  push:
    branches:
      - private/darshan/fixing-vulnerabilities-24-jul-2022

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: "Checkout source code"

      - name: setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16.16"

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: Deploy to Gitpages
        uses: peaceiris/actions-gh-pages@v3.7.3
        env:
          PERSONAL_TOKEN: ${{ secrets.PORTFOLIO_PAGE_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
